# Generated by Django 4.0.4 on 2022-04-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_mobile_options_alter_mobile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='name',
            new_name='title',
        ),
    ]
